# -*- coding: utf-8 -*-
"""3.0-Normalization-Min Max Scaler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BgAjmguK8GNOSsi7_aV5iZhh7UuNR49f

## Normalization-Min Max Scaler
"""

import seaborn as sns

df=sns.load_dataset('taxis')
df.head()

from sklearn.preprocessing import MinMaxScaler

min_max=MinMaxScaler()

min_max.fit(df[['distance','fare','tip']])

min_max.transform(df[['distance','fare','tip']])

min_max.fit_transform(df[['distance','fare','tip']])

min_max.transform([[1,3,4]])

